#!/usr/bin/env ruby

# Requires 3 arguments
# 
#   ./run [repository name] [ref type] [ref name]
#
# Sets the following environment variables
#
#   ENV['repository'] - name of the repository
#   ENV['ref_type']   - heads || tags
#   ENV['ref_name']   - name of the head or tag
#   ENV['tree']       - path to the working tree of cloned repo
#
require 'lib/garuda.rb'
# get to where we know we wanna be
Dir.chdir(File.dirname(__FILE__))
garuda = Garuda.new
garuda.clone_repository.run.cleanup